# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gato.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngato.proto\x12\x04grpc\"\x07\n\x05\x45mpty\",\n\x04Move\x12\x0e\n\x06player\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\t\x12\t\n\x01y\x18\x03 \x01(\t2Z\n\nGatoServer\x12\'\n\nRecordMove\x12\x0b.grpc.Empty\x1a\n.grpc.Move0\x01\x12#\n\x08MakeMove\x12\n.grpc.Move\x1a\x0b.grpc.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gato_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _MOVE._serialized_start=29
  _MOVE._serialized_end=73
  _GATOSERVER._serialized_start=75
  _GATOSERVER._serialized_end=165
# @@protoc_insertion_point(module_scope)
