# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gato_pb2 as gato__pb2


class GatoServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordMove = channel.unary_stream(
                '/grpc.GatoServer/RecordMove',
                request_serializer=gato__pb2.Empty.SerializeToString,
                response_deserializer=gato__pb2.Move.FromString,
                )
        self.MakeMove = channel.unary_unary(
                '/grpc.GatoServer/MakeMove',
                request_serializer=gato__pb2.Move.SerializeToString,
                response_deserializer=gato__pb2.Empty.FromString,
                )


class GatoServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordMove(self, request, context):
        """This bi-directional stream makes, allow to send and receive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatoServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordMove': grpc.unary_stream_rpc_method_handler(
                    servicer.RecordMove,
                    request_deserializer=gato__pb2.Empty.FromString,
                    response_serializer=gato__pb2.Move.SerializeToString,
            ),
            'MakeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMove,
                    request_deserializer=gato__pb2.Move.FromString,
                    response_serializer=gato__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.GatoServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GatoServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.GatoServer/RecordMove',
            gato__pb2.Empty.SerializeToString,
            gato__pb2.Move.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.GatoServer/MakeMove',
            gato__pb2.Move.SerializeToString,
            gato__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
